modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/RidableBlazes/issues"
license="MIT"

[[mods]]
modId="ridableblazes"
version="${file.jarVersion}"
displayName="Ridable Blazes"
displayURL="https://www.curseforge.com/minecraft/mc-mods/rideable-blazes"
authors="Mrbysco"
description='''
Allows you to equip a saddle onto a Blaze and ride it around
'''
[[dependencies.ridableblazes]]
modId="minecraft"
type="REQUIRED"
versionRange="[26.1.1,)"
ordering="NONE"
side="BOTH"
[[dependencies.ridableblazes]]
modId="neoforge"
type="REQUIRED"
versionRange="[26.1.1.0-alpha,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="ridableblazes.mixins.json"